import { ACCOUNT_URL } from "../utils/properties";
import { Templates } from "./template.paths";

export enum urlParams {
  PARAM_COMPANY_NUMBER = "companyNumber",
  PARAM_TRANSACTION_ID = "transactionId",
  PARAM_SUBMISSION_ID = "submissionId"
}

export enum URL_QUERY_PARAM {
  COMPANY_NUM = "companyNumber",
  IS_PSC = "isPsc"
}

const SEPARATOR = "/";

export const COMPANY_AUTH_PROTECTED_BASE = `/company/:${urlParams.PARAM_COMPANY_NUMBER}/`;
export const ACTIVE_SUBMISSION_BASE = COMPANY_AUTH_PROTECTED_BASE +
  `transaction/:${urlParams.PARAM_TRANSACTION_ID}/submission/:${urlParams.PARAM_SUBMISSION_ID}/`;
export const CONTAINS_TRANSACTION_ID = `/transaction/:${urlParams.PARAM_TRANSACTION_ID}`;
export const CONTAINS_SUBMISSION_ID = `/submission/:${urlParams.PARAM_SUBMISSION_ID}`;


// Use _PATH consts for redirects
// Use const without _PATH to match the url in the routes.ts
export const ACCESSIBILITY_STATEMENT = SEPARATOR + Templates.ACCESSIBILITY_STATEMENT;
export const ACCOUNTS_SIGNOUT_PATH = `${ACCOUNT_URL}/signout`;
export const CONFIRM_COMPANY = SEPARATOR + Templates.CONFIRM_COMPANY;
export const CONFIRMATION_STATEMENT = "/confirmation-statement";
export const COMPANY_NUMBER = "/company-number";
export const COMPANY_LOOKUP = "/company-lookup/search?forward=/confirmation-statement/confirm-company?companyNumber={companyNumber}";
export const CONFIRM_COMPANY_PATH = CONFIRMATION_STATEMENT + CONFIRM_COMPANY;
export const CONFIRMATION_STATEMENT_BODY = ACTIVE_SUBMISSION_BASE + "body/";
export const PEOPLE_WITH_SIGNIFICANT_CONTROL = CONFIRMATION_STATEMENT_BODY + Templates.PEOPLE_WITH_SIGNIFICANT_CONTROL;
export const PEOPLE_WITH_SIGNIFICANT_CONTROL_PATH = CONFIRMATION_STATEMENT + PEOPLE_WITH_SIGNIFICANT_CONTROL;
export const ACTIVE_PSC_DETAILS = CONFIRMATION_STATEMENT_BODY + Templates.ACTIVE_PSC_DETAILS;
export const ACTIVE_PSC_DETAILS_PATH = CONFIRMATION_STATEMENT + ACTIVE_PSC_DETAILS;
export const SHAREHOLDERS = CONFIRMATION_STATEMENT_BODY + "shareholders";
export const SHAREHOLDERS_PATH = CONFIRMATION_STATEMENT + SHAREHOLDERS;
export const SIC = CONFIRMATION_STATEMENT_BODY + "sic";
export const SIC_PATH = CONFIRMATION_STATEMENT + SIC;
export const SIGNOUT_PATH = "/signout";
export const CREATE_TRANSACTION = COMPANY_AUTH_PROTECTED_BASE + "transaction";
export const CREATE_TRANSACTION_PATH = CONFIRMATION_STATEMENT + CREATE_TRANSACTION;
export const TRADING_STATUS = CONFIRMATION_STATEMENT_BODY + "trading-status";
export const TRADING_STATUS_PATH = CONFIRMATION_STATEMENT + TRADING_STATUS ;
export const TASK_LIST = CONFIRMATION_STATEMENT_BODY + "task-list";
export const TASK_LIST_PATH = CONFIRMATION_STATEMENT + TASK_LIST;
export const STATEMENT_OF_CAPITAL = CONFIRMATION_STATEMENT_BODY + "statement-of-capital";
export const STATEMENT_OF_CAPITAL_PATH = CONFIRMATION_STATEMENT + STATEMENT_OF_CAPITAL;
export const ACTIVE_OFFICERS = CONFIRMATION_STATEMENT_BODY + "active-officers";
export const ACTIVE_OFFICERS_PATH = CONFIRMATION_STATEMENT + ACTIVE_OFFICERS;
export const ACTIVE_OFFICERS_DETAILS = CONFIRMATION_STATEMENT_BODY + "active-officers-details";
export const ACTIVE_OFFICERS_DETAILS_PATH = CONFIRMATION_STATEMENT + ACTIVE_OFFICERS_DETAILS;
export const REGISTERED_OFFICE_ADDRESS = CONFIRMATION_STATEMENT_BODY + "registered-office-address";
export const REGISTERED_OFFICE_ADDRESS_PATH = CONFIRMATION_STATEMENT + REGISTERED_OFFICE_ADDRESS;
export const CONFIRM_EMAIL_ADDRESS = CONFIRMATION_STATEMENT_BODY + "confirm-email-address";
export const CONFIRM_EMAIL_PATH = CONFIRMATION_STATEMENT + CONFIRM_EMAIL_ADDRESS;
export const PROVIDE_EMAIL_ADDRESS = CONFIRMATION_STATEMENT_BODY + "provide-email-address";
export const PROVIDE_EMAIL_ADDRESS_PATH = CONFIRMATION_STATEMENT + PROVIDE_EMAIL_ADDRESS;
export const CHECK_EMAIL_ADDRESS = CONFIRMATION_STATEMENT_BODY + "check-email-address";
export const CHECK_EMAIL_ADDRESS_PATH = CONFIRMATION_STATEMENT + CHECK_EMAIL_ADDRESS;
export const CHANGE_EMAIL_PATH = "/registered-email-address/email/change-email-address";
export const RETURN_FROM_REA = ACTIVE_SUBMISSION_BASE + "return-from-rea";
export const RETURN_FROM_REA_PATH = CONFIRMATION_STATEMENT + RETURN_FROM_REA;
export const REGISTER_LOCATIONS = CONFIRMATION_STATEMENT_BODY + "register-locations";
export const REGISTER_LOCATIONS_PATH = CONFIRMATION_STATEMENT + REGISTER_LOCATIONS;
export const CHANGE_ROA_PATH = COMPANY_AUTH_PROTECTED_BASE + "change-registered-office-address";
export const PSC_STATEMENT = CONFIRMATION_STATEMENT_BODY + Templates.PSC_STATEMENT;
export const PSC_STATEMENT_PATH = CONFIRMATION_STATEMENT + PSC_STATEMENT + `?${URL_QUERY_PARAM.IS_PSC}={${URL_QUERY_PARAM.IS_PSC}}`;
export const REVIEW = CONFIRMATION_STATEMENT_BODY + "review";
export const REVIEW_PATH = CONFIRMATION_STATEMENT + REVIEW;
export const CONFIRMATION = CONFIRMATION_STATEMENT_BODY + "confirmation";
export const CONFIRMATION_PATH = CONFIRMATION_STATEMENT + CONFIRMATION;
export const PAYMENT_CALLBACK = ACTIVE_SUBMISSION_BASE + "payment-callback";
export const PAYMENT_CALLBACK_PATH = CONFIRMATION_STATEMENT + PAYMENT_CALLBACK;
export const INVALID_COMPANY_STATUS = "/invalid-company-status";
export const INVALID_COMPANY_STATUS_PATH = CONFIRMATION_STATEMENT + INVALID_COMPANY_STATUS + `?${URL_QUERY_PARAM.COMPANY_NUM}={${URL_QUERY_PARAM.COMPANY_NUM}}`;
export const USE_PAPER = "/paper-filing";
export const USE_PAPER_PATH = CONFIRMATION_STATEMENT + USE_PAPER + `?${URL_QUERY_PARAM.COMPANY_NUM}={${URL_QUERY_PARAM.COMPANY_NUM}}`;
export const USE_WEBFILING = "/use-webfiling";
export const USE_WEBFILING_PATH = CONFIRMATION_STATEMENT + USE_WEBFILING + `?${URL_QUERY_PARAM.COMPANY_NUM}={${URL_QUERY_PARAM.COMPANY_NUM}}`;
export const NO_FILING_REQUIRED = "/no-filing-required";
export const NO_FILING_REQUIRED_PATH = CONFIRMATION_STATEMENT + NO_FILING_REQUIRED + `?${URL_QUERY_PARAM.COMPANY_NUM}={${URL_QUERY_PARAM.COMPANY_NUM}}`;
export const TRADING_STOP = CONFIRMATION_STATEMENT_BODY + Templates.TRADING_STOP;
export const TRADING_STOP_PATH = CONFIRMATION_STATEMENT + TRADING_STOP;
export const WRONG_SIC = CONFIRMATION_STATEMENT_BODY + Templates.WRONG_SIC;
export const WRONG_SIC_PATH = CONFIRMATION_STATEMENT + WRONG_SIC;
export const WRONG_STATEMENT_OF_CAPITAL = CONFIRMATION_STATEMENT_BODY + Templates.WRONG_STATEMENT_OF_CAPITAL;
export const WRONG_STATEMENT_OF_CAPITAL_PATH = CONFIRMATION_STATEMENT + WRONG_STATEMENT_OF_CAPITAL;
export const WRONG_SHAREHOLDERS = CONFIRMATION_STATEMENT_BODY + Templates.WRONG_SHAREHOLDERS;
export const WRONG_SHAREHOLDERS_PATH = CONFIRMATION_STATEMENT + WRONG_SHAREHOLDERS;
export const WRONG_RO =  CONFIRMATION_STATEMENT_BODY + Templates.WRONG_RO;
export const WRONG_RO_PATH = CONFIRMATION_STATEMENT + WRONG_RO;
export const WRONG_REGISTER_LOCATIONS = CONFIRMATION_STATEMENT_BODY + Templates.WRONG_REGISTER_LOCATIONS;
export const WRONG_REGISTER_LOCATIONS_PATH = CONFIRMATION_STATEMENT + WRONG_REGISTER_LOCATIONS;
export const WRONG_OFFICER_DETAILS = CONFIRMATION_STATEMENT_BODY + "incorrect-information/wrong-officer-details";
export const WRONG_OFFICER_DETAILS_PATH = CONFIRMATION_STATEMENT + WRONG_OFFICER_DETAILS;
export const WRONG_PSC_DETAILS = CONFIRMATION_STATEMENT_BODY + "incorrect-information/wrong-psc-details";
export const WRONG_PSC_DETAILS_PATH = CONFIRMATION_STATEMENT + WRONG_PSC_DETAILS;
export const WRONG_PSC_STATEMENT = CONFIRMATION_STATEMENT_BODY + "incorrect-information/wrong-psc-statement";
export const WRONG_PSC_STATEMENT_PATH = CONFIRMATION_STATEMENT + WRONG_PSC_STATEMENT;
export const ACSP_LIMITED_PARTNERSHIP = ACTIVE_SUBMISSION_BASE + "acsp";
export const ACSP_LIMITED_PARTNERSHIP_PATH = CONFIRMATION_STATEMENT + ACSP_LIMITED_PARTNERSHIP;
export const LP_BEFORE_YOU_FILE = ACSP_LIMITED_PARTNERSHIP + "/before-you-file";
export const LP_BEFORE_YOU_FILE_PATH = CONFIRMATION_STATEMENT + LP_BEFORE_YOU_FILE;
export const LP_CS_DATE = ACSP_LIMITED_PARTNERSHIP + "/confirmation-statement-date";
export const LP_CS_DATE_PATH = CONFIRMATION_STATEMENT + LP_CS_DATE;
export const LP_CHECK_AND_CONFIRM = ACSP_LIMITED_PARTNERSHIP + "/check-and-confirm";
export const LP_CHECK_AND_CONFIRM_PATH = CONFIRMATION_STATEMENT + LP_CHECK_AND_CONFIRM;
export const LP_CHECK_YOUR_ANSWER = ACSP_LIMITED_PARTNERSHIP + "/check-your-answer";
export const LP_CHECK_YOUR_ANSWER_PATH = CONFIRMATION_STATEMENT + LP_CHECK_YOUR_ANSWER;
export const LP_SIC_CODE_SUMMARY = ACSP_LIMITED_PARTNERSHIP + "/sic-code-summary";
export const LP_SIC_CODE_SUMMARY_PATH = CONFIRMATION_STATEMENT + LP_SIC_CODE_SUMMARY;
export const LP_SIC_CODE_SUMMARY_ADD = LP_SIC_CODE_SUMMARY + "/add";
export const LP_SIC_CODE_SUMMARY_ADD_PATH = CONFIRMATION_STATEMENT + LP_SIC_CODE_SUMMARY_ADD;
export const LP_SIC_CODE_SUMMARY_REMOVE = LP_SIC_CODE_SUMMARY + "/:code/remove";
export const LP_SIC_CODE_SUMMARY_SAVE = LP_SIC_CODE_SUMMARY + "/save";
export const LP_SIC_CODE_SUMMARY_SAVE_PATH = CONFIRMATION_STATEMENT + LP_SIC_CODE_SUMMARY_SAVE;
export const LP_ACSP_BASE = "/acsp";
export const LP_MUST_BE_AUTHORISED_AGENT = LP_ACSP_BASE + "/must-be-authorised-agent";
export const LP_MUST_BE_AUTHORISED_AGENT_PATH = CONFIRMATION_STATEMENT + LP_MUST_BE_AUTHORISED_AGENT;
export const LP_REVIEW = ACSP_LIMITED_PARTNERSHIP + "/review";
export const LP_REVIEW_PATH = CONFIRMATION_STATEMENT + LP_REVIEW;
export const LP_CONFIRMATION = ACSP_LIMITED_PARTNERSHIP + "/confirmation";
export const LP_CONFIRMATION_PATH = CONFIRMATION_STATEMENT + LP_CONFIRMATION;

export const middlewarePaths = /\/confirmation-statement\/((?!healthcheck).)*/;
